# Jekyll Config
# see https://jekyllrb.com/docs/configuration/
#
# Spamty API Doc (https://dev.spamty.eu/)
# Copyright (C) 2016 by Philipp & Spamty.eu


# Site settings
title: Spamty API Documentation
description: "This is the detailed documentation of the RESTful Spamty.eu API."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev.spamty.eu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# exclude some files
exclude: ["README.md", "CNAME", "docs/"]