FORMAT: 1A
HOST: https://api.spamty.eu/

# Spamty API
This is the API for Spamty.eu.

You can use it to generate a Spamty link (Encryption API) and to view an email address from a Spamty link (Decryption API).

Feel free to edit our API documentation on [GitHub](https://github.com/spamty/api-docs).

## Support
You can [contact us](https://spamty.eu/contact.php) if you need help or if you have any questions.
Please look at our [statuspage](https://stats.uptimerobot.com/E9XBli1k6) to find out if there are any problems with our servers.

Stay up-to-date with our [feed](https://spamty.eu/feed.php) to get notified about updates.

## Authentication
You need to authenticate with an username and an API key to use our API.
Please [request them via our contact form](https://spamty.eu/contact.php).

The decryption API is only for internal use. You need an additional authentication with HTTP Basic Auth header to use them.




# Group Encryption
This is the API to generate a new Spamty link with your email address.

The current version is v7. Notice that the link that will be created contains the version.
A v2 link can be used only with our decryption API v2, v3 with v3 and so on. Older versions of our encryption API are not available anymore.


## Encryption v7 [/encryption/v7.php]
This is the API to generate a new Spamty link with your email address.

### POST
You need to do a post request.

+ Attributes

  + mode (string) - Use `email` for a link to an email address or `text` for any other information like phone number or address. (required)
  + ciphertext (string) - The javascript-encrypted content. Urlencoded. (required)
  + salt (string) - The salt used for javascript-encryption. Urlencoded. (required)
  + email (string) - A valid email address; permission to store the email address in cleartext is implied. Urlencoded. (optional)
  + apiUser (string) - Your class E API username. (required)
  + apiKey (string) - Your class E secret API key. (required)

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your data the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/encryption/encryption-v7",
            "version": "v6",
            "apiM": "20",
            "urlPublic": "https://spamty.eu/mail/v6/20/YOURKEY/YOURIV/"
            }

    + Schema

            {
            "title": "Response /encryption API",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API.",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "apiM": {
                    "description": "The m parameter for the decryption request.",
                    "type": "integer"
                },
                "urlPublic": {
                    "description": "The public decryption url with placeholders for key and iv from javascript encrytion.",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }


## Encryption v6 [/encryption/v6.php]
This is the API to generate a new Spamty link with your email address.

### POST
You need to do a post request.

+ Attributes

  + mode (string) - use `email` to get a link to an email address or `text` to enter any other information like phone number or address.
  + email (string) - The validated email address (`test@example.com`). Always required.
  + text (string) - The text if you are using `text` mode.
  + allowCleartext (boolean) - `true` or `1` to allow Spamty to store the email address in cleartext; otherwise leave this empty. `true` is required when using `text` mode.
  + apiUser (string) - Your class E API username.
  + apiKey (string) - Your class E secret API key.

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your data the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/encryption/encryption-v6",
            "version": "v6",
            "apiM": "20",
            "apiK": "869656557u8375992c",
            "urlPublic": "https://spamty.eu/mail/v6/20/869656557u8375992c/",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /encryption API",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API.",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "apiM": {
                    "description": "The m parameter for the decryption request.",
                    "type": "integer"
                },
                "apiK": {
                    "description": "The k parameter for the decryption request. A string with no special chars.",
                    "type": "string"
                },
                "urlPublic": {
                    "description": "The public decryption url which can be shared.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }








# Group Decryption
This is the API to get an email address from a Spamty link.
You need to use the API that corresponds to the encryption API that was used. For example if your Spamty link was created with the encryption API version 4 ("v4" is contained in the URL: `https://spamty.eu/mail/v4/20/869656557u8375992c/`) then you are required to use the decryption API version 4. Otherwise you will get an error.
All decryption APIs are only for internal use. You need an additional authentication with HTTP Basic Auth header to use them.


## Decryption v5 [/decryption/v5.php]
With this API you can get an email address from a Spamty link.

### POST
You need to send a POST request.

+ Attributes
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v5",
            "version": "5",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v5",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address or the text (for `text` mode).",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }

## Decryption v4 [/decryption/v4.php]
With this API you can get an email address from a Spamty link.

### POST
You need to send a POST request.

+ Attributes
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v4",
            "version": "4.2",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v4",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }

## Decryption v3 [/decryption/v3.php]
[Pre-announcement](https://spamty.eu/feed.php) that this API will probably become invalid in late 2020.

### POST
You need to send a POST request.

+ Attributes
      + n (number) - The apiN parameter of the encryption request (a number).
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v3",
            "version": "v3",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v3",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }

## Decryption v2 [/decryption/v2.php]
[Pre-announcement](https://spamty.eu/feed.php) that this API will become invalid in late 2020.

### POST

+ Attributes
      + n (number) - The apiN parameter of the encryption request (a number).
      + m (string) - The apiM parameter of the encryption request (string with a-z A-z 0-9).
      + k (string) - The apiK parameter of the encryption request (string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v2",
            "version": "v2",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v2",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }




## Decryption v1 [/decryption/v1.php]
As [announced](https://spamty.eu/feed.php#item3) this API will become invalid on 2020/09/30.

### POST

+ Attributes
      + n (number) - The apiN parameter of the encryption request (a number).
      + m (string) - The apiM parameter of the encryption request (string with a-z A-z 0-9).
      + k (string) - The apiK parameter of the encryption request (string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v1",
            "version": "v1",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v1",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }
