FORMAT: 1A
HOST: https://spamty.eu/

# Spamty API
This is the API documentation for Spamty.eu.

You can use it to generate a new Spamty link (Encryption API) and to view an email address from a Spamty link (Decryption API).
The documentation contains information for our internal PHP functions and the accessible REST API.

Feel free to edit our API documentation on [GitHub](https://github.com/spamty/api-docs).

## Support
You can [contact us](https://spamty.eu/contact.php) if you need help or if you have any questions.
Please look at our [statuspage](https://stats.uptimerobot.com/E9XBli1k6) to find out if there are any problems with our servers.

Stay up-to-date with our [feed](https://spamty.eu/feed.php) to get notified about updates.

## Authentication
You need to authenticate with an username and an API key to use our API.
Please [request them via our contact form](https://spamty.eu/contact.php).

The decryption API is only for internal use. You need an additional authentication with HTTP Basic Auth header to use them.



# Group Encryption: PHP functions

## spamtyEncrypt() [includes/functions_v6.php]

+ Attributes
  + $encData (string) - email address or text to be encrypted
  + $encMode (string) - either "email" or "text" mode
  + $emailCleartext (string) - email address if it should be stored in cleartext

+ Response 200 (array)
  + status (integer) - 200
  + statusDetails (string) - ok
  + url (string) - URL of the Spamty link

+ Error 4301 (array)
  + status (integer) - 4301
  + statusDetails (string) - apiUser or apiKey is not set
  + url (empty string)

+ Error 4302 (array)
  + status (integer) - 4302
  + statusDetails (string) - apiUser or apiKey is invalid
  + url (empty string)

+ Error 4701 (array)
  + status (integer) - 4701
  + statusDetails (string) - This was no valid email address
  + url (empty string)

+ Error 4702 (array)
  + status (integer) - 4702
  + statusDetails (string) - The text was too long
  + url (empty string)

+ Error 4703 (array)
  + status (integer) - 4703
  + statusDetails (string) - This was no valid email address
  + url (empty string)

+ Error 5701 (array)
  + status (integer) - 5701
  + statusDetails (string) - Problem when connecting to the database
  + url (empty string)

+ Error 5702 (array)
  + status (integer) - 5702
  + statusDetails (string) - Problem when executing database statement
  + url (empty string)




# Group Encryption: REST API
This is the API to generate a new Spamty link with your email address.

The current version is v6 (v7 with Javascript is not available as public REST API).
Older versions of our encryption API are not available anymore.

Notice that the link that will be created contains the version.
A v4 link can be used only with our decryption API v4, v5 with v5 and so on.


## Encryption v6 [/api/encryption/v6.php]
This is the API to generate a new Spamty link with your email address.

### POST

+ Attributes

  + encMode (string) - use "email" to get a link to an email address or "text" to enter any other information like phone number or address
  + encData (string) - the email address (for "email" mode) or any other text (for "text" mode)
  + emailCleartext (string) - email address if it should be stored in cleartext; is required when using "text" mode
  + apiUser (string) - your API username
  + apiKey (string) - your secret API key

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.

    + Body

            {
            "status": 200,
            "statusDetails": "ok",
            "url": "https://spamty.eu/show/v6/321/503403c9cda77fde79fc6297/"
            }

+ Response 400 (application/json)
If there was any error the status code will be 400. Please look at the error code and the error message to indentify the problem.

    + Body

            {
            "status": 4701,
            "statusDetails": "This was no valid email address",
            "url": ""
            }







# Group Decryption: PHP functions

## spamtyDecrypt() [includes/functions_v6.php]

+ Attributes
  + $m (integer) - id in database
  + $k (string; [a-z0-9]{24}) - encryption key

+ Response 200 (array)
  + status (integer) - 200
  + statusDetails (string) - ok
  + cleartext (string) - decrypted email address or text
  + mode (string) - either "email" or "text" mode

+ Error 4801 (array)
  + status (integer) - 4801
  + statusDetails (string) - This link was invalid (m)
  + cleartext (empty string)
  + mode (empty string)

+ Error 4802 (array)
  + status (integer) - 4802
  + statusDetails (string) - This link was invalid (k)
  + cleartext (empty string)
  + mode (empty string)

+ Error 5801 (array)
  + status (integer) - 5801
  + statusDetails (string) - Problem when connecting to the database
  + cleartext (empty string)
  + mode (empty string)

+ Error 5802 (array)
  + status (integer) - 5802
  + statusDetails (string) - We found no data in our database
  + cleartext (empty string)
  + mode (empty string)


## spamtyDecrypt() [includes/functions_v5.php]
## spamtyDecrypt() [includes/functions_v4.php]

+ Attributes
  + $m (integer) - id in database
  + $k (string; [a-zA-Z0-9]{18}) - encryption key

+ Response 200 (array)
  + status (integer) - 200
  + statusDetails (string) - ok
  + cleartext (empty string) - decrypted email address or text
  + mode (empty string) - either "email" or "text" mode

+ for errors see above





# Group Decryption: REST API
There is no public Decryption REST API.
This is only available trough the internal PHP functions.
