FORMAT: 1A
HOST: https://spamty.eu/

# Spamty API
This is the API documentation for Spamty.eu.

You can use it to generate a new Spamty link (Encryption API) and to view an email address from a Spamty link (Decryption API).
The documentation contains information for our internal PHP functions and the accessible REST API.

Feel free to edit our API documentation on [GitHub](https://github.com/spamty/api-docs).

## Support
You can [contact us](https://spamty.eu/contact.php) if you need help or if you have any questions.
Please look at our [statuspage](https://stats.uptimerobot.com/E9XBli1k6) to find out if there are any problems with our servers.

Stay up-to-date with our [feed](https://spamty.eu/feed.php) to get notified about updates.

## Authentication
You need to authenticate with an username and an API key to use our API.
Please [request them via our contact form](https://spamty.eu/contact.php).

The decryption API is only for internal use. You need an additional authentication with HTTP Basic Auth header to use them.



# Group Encryption: PHP functions

## spamtyEncrypt() [includes/functions_v6.php]

+ Attributes
  + $encData (string) - email address or text to be encrypted
  + $encMode (string) - either "email" or "text" mode
  + $emailCleartext (string) - email address if it should be stored in cleartext

+ Response 200 (array)
  + status (integer) - 200
  + statusDetails (string) - ok
  + url (string) - URL of the Spamty link

+ Error 4701 (array)
  + status (integer) - 4701
  + statusDetails (string) - This was no valid email address
  + url (empty string)

+ Error 4702 (array)
  + status (integer) - 4702
  + statusDetails (string) - The text was too long
  + url (empty string)

+ Error 4703 (array)
  + status (integer) - 4703
  + statusDetails (string) - This was no valid email address
  + url (empty string)

+ Error 5701 (array)
  + status (integer) - 5701
  + statusDetails (string) - Problem when connecting to the database
  + url (empty string)

+ Error 5702 (array)
  + status (integer) - 5702
  + statusDetails (string) - Problem when executing database statement
  + url (empty string)




# Group Encryption: REST API
This is the API to generate a new Spamty link with your email address.

The current version is v7. Notice that the link that will be created contains the version.
A v2 link can be used only with our decryption API v2, v3 with v3 and so on. Older versions of our encryption API are not available anymore.


## Encryption v7 [/xxxxxx]
This is the API to generate a new Spamty link with your email address.

### POST
You need to do a post request.

+ Attributes

  + mode (string) - Use `email` for a link to an email address or `text` for any other information like phone number or address. (required)
  + ciphertext (string) - The javascript-encrypted content. Urlencoded. (required)
  + salt (string) - The salt used for javascript-encryption. Urlencoded. (required)
  + email (string) - A valid email address; permission to store the email address in cleartext is implied. Urlencoded. (optional)
  + apiUser (string) - Your class E API username. (required)
  + apiKey (string) - Your class E secret API key. (required)

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your data the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/encryption/encryption-v7",
            "version": "v6",
            "apiM": "20",
            "urlPublic": "https://spamty.eu/mail/v6/20/YOURKEY/YOURIV/"
            }

    + Schema

            {
            "title": "Response /encryption API",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API.",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "apiM": {
                    "description": "The m parameter for the decryption request.",
                    "type": "integer"
                },
                "urlPublic": {
                    "description": "The public decryption url with placeholders for key and iv from javascript encrytion.",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }


## Encryption v6 [/api/encryption/v6.php]
This is the API to generate a new Spamty link with your email address.

### POST

+ Attributes

  + mode (string) - use `email` to get a link to an email address or `text` to enter any other information like phone number or address
  + encData (string) - the email (for `email` mode) or any other text (for `text` mode)
  + emailCleartext (string) - the email address to store in cleartext; is required when using `text` mode
  + apiUser (string) - your API username
  + apiKey (string) - your secret API key

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.

    + Body

            {
            "status": 200,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/encryption/encryption-v6",
            "version": "v6",
            "apiM": "321",
            "apiK": "503403c9cda77fde79fc6297",
            "urlPublic": "https://spamty.eu/show/v6/321/503403c9cda77fde79fc6297/"
            }

+ Response 400 (application/json)
If there was any error the status code will be 400. Please look at the error code and the error message to indentify the problem.

    + Body

            {

            }







# Group Decryption: PHP functions

## spamtyDecrypt() [includes/functions_v6.php]

+ Attributes
  + $m (integer) - id in database
  + $k (string; [a-z0-9]{24}) - encryption key

+ Response 200 (array)
  + status (integer) - 200
  + statusDetails (string) - ok
  + cleartext (string) - decrypted email address or text
  + mode (string) - either "email" or "text" mode

+ Error 4801 (array)
  + status (integer) - 4801
  + statusDetails (string) - This link was invalid (m)
  + cleartext (empty string)
  + mode (empty string)

+ Error 4802 (array)
  + status (integer) - 4802
  + statusDetails (string) - This link was invalid (k)
  + cleartext (empty string)
  + mode (empty string)

+ Error 5801 (array)
  + status (integer) - 5801
  + statusDetails (string) - Problem when connecting to the database
  + cleartext (empty string)
  + mode (empty string)

+ Error 5802 (array)
  + status (integer) - 5802
  + statusDetails (string) - We found no data in our database
  + cleartext (empty string)
  + mode (empty string)


## spamtyDecrypt() [includes/functions_v5.php]
## spamtyDecrypt() [includes/functions_v4.php]

+ Attributes
  + $m (integer) - id in database
  + $k (string; [a-zA-Z0-9]{18}) - encryption key

+ Response 200 (array)
  + status (integer) - 200
  + statusDetails (string) - ok
  + cleartext (empty string) - decrypted email address or text
  + mode (empty string) - either "email" or "text" mode

+ Error 4801 (array)
  + status (integer) - 4801
  + statusDetails (string) - This link was invalid (m)
  + cleartext (empty string)
  + mode (empty string)

+ Error 4802 (array)
  + status (integer) - 4802
  + statusDetails (string) - This link was invalid (k)
  + cleartext (empty string)
  + mode (empty string)

+ Error 5801 (array)
  + status (integer) - 5801
  + statusDetails (string) - Problem when connecting to the database
  + cleartext (empty string)
  + mode (empty string)

+ Error 5802 (array)
  + status (integer) - 5802
  + statusDetails (string) - We found no data in our database
  + cleartext (empty string)
  + mode (empty string)




# Group Decryption: REST API
This is the API to get an email address from a Spamty link.
You need to use the API that corresponds to the encryption API that was used. For example if your Spamty link was created with the encryption API version 4 ("v4" is contained in the URL: `https://spamty.eu/mail/v4/20/869656557u8375992c/`) then you are required to use the decryption API version 4. Otherwise you will get an error.
All decryption APIs are only for internal use. You need an additional authentication with HTTP Basic Auth header to use them.

These versions of the decryption API are not available anymore: v1.

## Decryption v7 [/xxxxxxxxxxxxxxx]
With this API you can get an email address from a Spamty link.

### POST
You need to send a POST request.

+ Attributes
      + m (number) - The apiM parameter of the encryption request (a number).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class D API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v7",
            "version": "v7",
            "ciphertext": "338bd9e8ba4096323da691c2c0bae8411dfac468c5473be75cd37518d50b8ed4",
            "salt": "52cc21e0806e4a0e"
            }

    + Schema

            {
            "title": "Response /decryption API v7",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "ciphertext": {
                    "description": "The javascript-encrypted email address or the text.",
                    "type": "string"
                },
                "salt": {
                    "description": "The salt for javascript decryption.",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }




## Decryption v6 [/xxxxxxxxxxxxxxx]
With this API you can get an email address from a Spamty link.

### POST
You need to send a POST request.

+ Attributes
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v6",
            "version": "v6",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v6",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address or the text (for `text` mode).",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }


## Decryption v5 [/xxxxxxxxxxxxxxx]
With this API you can get an email address from a Spamty link.

### POST
You need to send a POST request.

+ Attributes
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v5",
            "version": "5",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v5",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address or the text (for `text` mode).",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }

## Decryption v4 [/xxxxxxxxxxxxxxx]
With this API you can get an email address from a Spamty link.

### POST
You need to send a POST request.

+ Attributes
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v4",
            "version": "4.2",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v4",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version number.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }

## Decryption v3 [/x]
As [announced](https://spamty.eu/feed.php#item6) this API will become invalid on 2020/11/30.

### POST
You need to send a POST request.

+ Attributes
      + n (number) - The apiN parameter of the encryption request (a number).
      + m (number) - The apiM parameter of the encryption request (a number).
      + k (string) - The apiK parameter of the encryption request (a string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v3",
            "version": "v3",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v3",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }

## Decryption v2 [/x]
As [announced](https://spamty.eu/feed.php#item6) this API will become invalid on 2020/11/30.

### POST

+ Attributes
      + n (number) - The apiN parameter of the encryption request (a number).
      + m (string) - The apiM parameter of the encryption request (string with a-z A-z 0-9).
      + k (string) - The apiK parameter of the encryption request (string with a-z A-z 0-9).
      + apiUser (string) - Your class D Username.
      + apiKey (string) - Your class E API Key.

+ Request (application/x-www-form-urlencoded)

    + Headers

            Authentication: HTTP Basic


+ Response 200 (application/json)
This is an example for a successful response. The HTTP status code will be 200.
If there was an error with your parameters the status code will be 400. Please look at the value for "statusDetails" to indentify the problem.
If there was a problem with our server or database the status code will be 500. Contact the support and report this problem.

    + Body

            {
            "status": 1,
            "statusDetails": "ok",
            "info": "https://spamty.docs.apiary.io/#reference/decryption/decryption-v2",
            "version": "v2",
            "email": "demo@spamty.eu",
            "mailCheck": "50fbf5f7"
            }

    + Schema

            {
            "title": "Response /decryption API v2",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Value 1 for OK and 0 if an error occurred.",
                    "type": "integer"
                },
                "statusDetails": {
                    "description": "A description if there were any errors. Otherwise the value is ok.",
                    "type": "string"
                },
                "info": {
                    "description": "The URL where you can get some additional information about the API (this page).",
                    "type": "string"
                },
                "version": {
                    "description": "The version.",
                    "type": "string"
                },
                "email": {
                    "description": "The email address.",
                    "type": "string"
                },
                "mailCheck": {
                    "description": "A crc32b hash of the email address",
                    "type": "string"
                }
            },
            "required": ["status", "statusDetails", "info", "version"],
            }
